
# NumPy Basics - Learning Notebook 📘

## 🧠 Introduction to NumPy
Welcome to this notebook on NumPy, short for Numerical Python — one of the core libraries in the Python data science ecosystem. NumPy provides support for large, multi-dimensional arrays and matrices, along with a vast collection of high-level mathematical functions to operate on these arrays efficiently.

---

## 💡 What is NumPy?
NumPy is a powerful numerical computing library that allows us to perform operations on large datasets with ease. It brings high performance through its C-backed arrays, and replaces slower Python list operations with optimized methods.

---

## 🚀 Why Use NumPy?
* 🔢 Efficient array handling – much faster and more memory-efficient than Python lists
* 🧮 Vectorized operations – perform batch operations without writing loops
* 📊 Mathematical capabilities – supports linear algebra, Fourier transforms, and more
* 🔁 Broadcasting – allows you to perform arithmetic across different array shapes
* 🤝 Integration – works seamlessly with libraries like Pandas, SciPy, and scikit-learn
  
---

## 📚 What You Will Learn
In this notebook, you’ll explore:

* Creating NumPy arrays and understanding their structure 
* Array indexing, slicing, and reshaping
* Performing mathematical and statistical operations
* Useful NumPy functions for manipulating data
* Broadcasting and vectorization
* Loading/storing arrays from files

---

## 🎯 Goal of the Notebook
By the end of this notebook, you'll have a solid grasp of NumPy fundamentals, which will serve as the foundation for data science, machine learning, and scientific computing workflows. You'll be able to confidently use NumPy for data preprocessing, numerical analysis, and building efficient computation pipelines.

---
#### Let’s dive in! 🧪


## Installing NumPy

In [ ]:
!pip install numpy


## 🔧 Importing NumPy

We begin by importing NumPy—Python's fundamental package for scientific computing.

- `import numpy as np`: This is the standard alias used to call NumPy functions easily throughout your code.


In [2]:
import numpy as np


## 🔢 Creating NumPy Arrays

This section demonstrates how to create NumPy arrays from Python lists. NumPy arrays are more efficient and powerful for numerical operations than Python lists.

- `np.array([1, 2, 3])`: Creates a 1D array of integers.
- `np.array([[1,2,3], [4,5,6]])`: Creates a 2D matrix.
- Arrays can have different datatypes like integers or floats.

📌 **Use Case:** Arrays form the building blocks of tensors used in data science, ML models, and scientific computing.


In [3]:
# 1D Array - Integer datatype
arr1_int = np.array([1,2,3,4])
print(f"1D Array of int datatype: {arr1_int}")

# 1D Array - Float datatype
arr1_float = np.array([1.,2.,3.])
print(f"1D Array of float datatype: {arr1_float}")

# 2D Array - 2 rows and 3 columns
arr2 = np.array([[1,2,3],
                [4,5,6]])
print(f"2D array:\n{arr2}")

1D Array of int datatype: [1 2 3 4]
1D Array of float datatype: [1. 2. 3.]
2D array:
[[1 2 3]
 [4 5 6]]



## 📐 Array Attributes

We inspect properties of arrays that help in understanding and debugging them.

- `.ndim`: Returns number of dimensions (1D, 2D, etc).
- `.shape`: Gives (rows, columns) for 2D arrays.
- `.size`: Total number of elements in the array.
- `.dtype`: Data type (e.g., `int32`, `float64`) of elements in the array.

📌 **Use Case:** These attributes help automate and debug array-based computations in data pipelines.


In [4]:
# Basic Attributes

# dimention 
print(f"1D array dimension: {arr1_float.ndim}")
print(f"2D array dimension: {arr2.ndim}")
print("\n")

# shape of array 
print(f"1D array shape: {arr1_int.shape}")
print(f"2D array shape: {arr2.shape}")
print("\n")

# Total number of elements in array
print(f"Total elements in arr2 (2D array): {arr2.size}")
print("\n")

# Date type of the elements
print(f"Data type of array arr1_int: {arr1_int.dtype}")
print(f"Data type of array arr1_float: {arr1_float.dtype}")


1D array dimension: 1
2D array dimension: 2


1D array shape: (4,)
2D array shape: (2, 3)


Total elements in arr2 (2D array): 6


Data type of array arr1_int: int32
Data type of array arr1_float: float64



## 🔄 Reshaping and Flattening Arrays

Transform the shape of an array without altering its data.

- `.reshape(m, n)`: Changes the shape to m×n (e.g., reshape 3x4 to 2x6).
- `.flatten()` or `.ravel()`: Converts an n-dimensional array to 1D.

📌 **Use Case:** Essential for preparing data in ML models where specific shapes (like 1D or 2D) are required.


In [5]:
# array of shape 3 x 4
arr = np.array([[12,45,67,89],[46,66,98,14],[89,23,67,88]])

# Reshaping the array using reshape()
print("Reshaped array of size 2x6 ",arr.reshape(2,6))
print("Change in original array ",arr)

# Flatten the array into 1D
arr_flatten = arr.flatten()
print("Flatten array ",arr_flatten)


Reshaped array of size 2x6  [[12 45 67 89 46 66]
 [98 14 89 23 67 88]]
Change in original array  [[12 45 67 89]
 [46 66 98 14]
 [89 23 67 88]]
Flatten array  [12 45 67 89 46 66 98 14 89 23 67 88]



## 🧱 Special Arrays & Random Numbers

Create arrays filled with default or random values.

- `np.zeros((2,3))`: 2x3 array of zeros.
- `np.ones(10)`: 1D array of ten ones.
- `np.full((2,3), 5)`: 2x3 array filled with the value 5.
- `np.random.rand(5)`: Array of 5 random float values in [0, 1).
- `np.random.randint(5,10,(2,3))`: 2x3 array of random integers in [5,10).
- `np.arange(5,10,3)`: Creates array [5, 8] with step of 3.
- `np.linspace(0,10,5)`: Divides 0 to 10 into 5 evenly spaced float values.

📌 **Use Case:** Used in simulations, synthetic data generation, initializing weights in ML models.


In [6]:
# Array of zeros
zeros_1d = np.zeros(5)
zeros_2d = np.zeros((2,3))

print(f"1D Array of zeros: {zeros_1d}")
print(f"2D Array of zeros: {zeros_2d}")

ones_arr = np.ones(10)
print(f"1D Array of ones: {ones_arr}")

# Filling the array with default value
arr_5 = np.full((2,3),5)
print(f"2D Array of 5: {arr_5}")

# Array of 5 number between 0 and 1 (excluding 1)
rand = np.random.rand(5)
print(f"Array of random numbers between 0 and 1 (excluding one) {rand}")

# Array of 5 numbers between any numbers
randint = np.random.randint(5,10,(2,3))
print(f"2D Array of random numbers between 5 and 10: {randint}")

# Array of numbers between any numbers with distance as 3
arange = np.arange(5,10,3)
print(f"Array of numbers between 5 and 10 with 3 steps: {arange}")

# Array of float numbers between any 2 numbers
linspace = np.linspace(0,10,5)
print(f"Array of 5 floating numbers: {linspace}")

1D Array of zeros: [0. 0. 0. 0. 0.]
2D Array of zeros: [[0. 0. 0.]
 [0. 0. 0.]]
1D Array of ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
2D Array of 5: [[5 5 5]
 [5 5 5]]
Array of random numbers between 0 and 1 (excluding one) [0.38126927 0.0930028  0.74276269 0.9060193  0.97019979]
2D Array of random numbers between 5 and 10: [[5 8 9]
 [5 8 6]]
Array of numbers between 5 and 10 with 3 steps: [5 8]
Array of 5 floating numbers: [ 0.   2.5  5.   7.5 10. ]



## ➕ Basic Arithmetic Operations

Perform element-wise operations between arrays of the same shape.

- `a + b`: Adds corresponding elements.
- `a - b`: Subtracts corresponding elements.
- `a * b`: Multiplies element-wise.
- `a / b`: Divides element-wise.

📌 **Use Case:** Supports vectorized computation, which is faster than looping. Used in ML (like vector math), graphics (image pixel operations), and numerical modeling (e.g., matrix equations).


In [8]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

# Add 
print(f"Add: {a1+a2}")

# Subtract
print(f"Subtract: {a1-a2}")

# Multiply
print(f"Multiply: {a1*a2}")

# Divide
print(f"Divide: {a1/a2}")

Add: [5 7 9]
Subtract: [-3 -3 -3]
Multiply: [ 4 10 18]
Divide: [0.25 0.4  0.5 ]


## 📊 Aggregate Functions on Arrays
This section includes statistical functions for summarizing array data:

* `sum()` → Total of all elements.
* `min()` → Minimum element.
* `max()` → Maximum element.
* `mean()` → Average of values.
* `std()` → Standard deviation (spread of data).
* `var()` → Variance (spread squared).

📌 Use Case: Useful in analytics, reporting, feature scaling, and evaluation metrics.


In [13]:
# Sum of array
print(f"sum {a1.sum()}")

# Minimum element of array
print(f"min {a1.min()}")

# Maximum element of array
print(f"max {a1.max()}")

# Mean of array
print(f"mean {a1.mean()}")

# Standard deviation of array
print(f"standard deviation {a1.std():.2f}")

# Variance of array
print(f"variance {a1.var():.2f}")

sum 6
min 1
max 3
mean 2.0
standard deviation 0.82
variance 0.67


## 🧭 Indexing and Slicing

* Indexing and Slicing - 
Retrieve specific values or sub-arrays:

* `a1[1]` → Gets the second element.
* `a1[0:3]` → First 3 elements.
* `a1[-3:]` → Last 3 elements.

📌 Use Case: Extract sequences, modify data, or select features.

In [27]:
# Accessing the 2nd element of array
print(f"2nd element of array {a1[1]}")

# Accessing first 3 elements element of array
print(f"First 3 elements of the array {a1[0:3]}")

# Accessing last 3 elements of array
print(f"Last 3 elemets of the array {a1[-3:]}")

@nd element of array 2
First 3 elements of the array [1 2 3]
Last 3 elemets of the array [1 2 3]


## 🕵️ Boolean Masking & Filtering
Apply conditions directly to arrays:

* `a1 > 2` → Returns a boolean array.

* `a1[a1 > 2]` → Filters elements based on condition.

📌 Use Case: Data filtering, conditional logic in pipelines.

In [32]:
# Accessing the elements which are greater than 2
mask = a1 > 2
print(f"Element which is greater than 2 {a1[mask]}")

# Boolean Indexing
print(f"Boolean Array {mask}")

Element which is greater than 2 [3]
Boolean Array [False False  True]


## 🧰 Handy NumPy Utilities

* `np.unique()` → Unique values.
* `np.where(condition, x, y)` → Ternary logic on arrays.
* `np.isin(array, [values])` → Membership testing.
* `np.clip(array, min, max)` → Restricts range of values.

📌 Use Case: Cleansing, transforming, or validating model inputs/outputs.



In [43]:
print("Unique elements in array ",np.unique(a1))                # Unique elements
print("Applying Condition ",np.where(a1 > 5, 1, 0))            # Apply condition
print("Element present or not ",np.isin(a1, [1, 2]))          # Check membership
print("Clipping values within range ",np.clip(a1, 0, 10))     # Clip values within range

Unique elements in array  [0 1 2 3 4 5 6 7 8 9]
Applying Condition  [0 0 0 0 1 1 0 1 0 1 0 0 0]
Element present or not  [ True  True False False False False False False False False False  True
 False]
Clipping values within range  [1 2 4 5 6 7 3 8 3 9 3 1 0]


# Saving and Loading

In [45]:
np.save("array.npy", a1)             # Save array to .npy file
np.load("array.npy")                # Load array from .npy file
np.savetxt("array.txt", a1)          # Save as text file
np.loadtxt("array.txt")             # Load from text file

array([1., 2., 4., 5., 6., 7., 3., 8., 3., 9., 3., 1., 0.])


---
# ✅ Conclusion
In this notebook, we explored the core functionalities of NumPy—from creating arrays and performing mathematical operations, to slicing, reshaping, broadcasting, and using built-in functions for efficient computation.

You should now have:

* A solid understanding of how NumPy arrays work and how they differ from Python lists
* Hands-on experience with common array operations and transformations
* Knowledge of broadcasting and vectorization for writing cleaner, faster code
* Confidence in using NumPy as a foundation for data science, ML, and scientific tasks

If you’re ready to dive deeper into numerical computing or want to explore more advanced topics like linear algebra, random number generation, and performance optimization using NumPy, check out the official documentation:
🔗 NumPy Documentation: https://numpy.org/doc/stable/

Happy coding! 🧠⚙️📊

